minor updates

diff --git a/bashlive b/bashlive
--- a/bashlive
+++ b/bashlive
@@ -210,7 +210,7 @@ trysourcewebpipe(){
 bashlive::get(){
   arg="${1/\!/}"; [[ ${#arg} == 0 ]] && { echo "bashlive usage: / <searchterm- or bashlive path/index>"; return 0; }
   # bake into file if needed
-  is_file "$arg" && scripthasbashlive "$arg" && bashlive::bake "$arg" 
+  is_file "$arg" && { scripthasbashlive "$arg" && bashlive::bake "$arg" && return 0; }
   # search if no path given
   ! is_integer "$arg" && ! is_url "$arg" && [[ ! "$1" =~ ^/ ]] && { bashlive::search "$@"; return 0; } 
   checkinteractive "$@"; arg="${1/\!/}"                               # very strange, why does the '!' gets inserted into $arg again?
@@ -224,15 +224,14 @@ bashlive::get(){
   # re-use cache, dont source twice
   cachefile="$BASHLIVETMP$path"
   if [[ -f "$cachefile" ]] && [[ ! -n "$2" ]]; then 
-    source "$cachefile";
-  else
-    # finally get the web content
+    content="$(cat "$cachefile")"
+  else # get the web content
     content="$( ${CURL} "$url")" || { printf "$C_RED""could not retrieve bashlive url '$data'$C_NORMAL\n"; return 1; }
-    # print it 
-    [[ $INTERACTIVE == "0" ]] || { printf "\n%s\n%s\n\n" "# source: ${url/\/raw*/}" "$content"; } | more | highlightcode
-    bashlive::savecache "$content" "$path"
-    trysource "$content" "$url" "$path" 
   fi
+  # print it 
+  [[ $INTERACTIVE == "0" ]] || { printf "\n%s\n%s\n\n" "# source: ${url/\/raw*/}" "$content"; } | more | highlightcode
+  [[ ! -f "$cachefile" ]] && bashlive::savecache "$content" "$path"
+  trysource "$content" "$url" "$path" 
   # run args if provided to forced source (e.g. '/ /foo/bar! arg1 arg2')
   [[ -n "$2" ]] && bashlive::runargs "$@"
 }
@@ -313,20 +312,21 @@ checkdependencies(){
 bashlive::bake(){
   file="$(readlink -f "$1")"; 
   scripthasbashlive "$file" || { printf "$C_RED""could not find 'source bashlive' in your script :($C_NORMAL\n"; return 1; }
-  read -p "bake bashlive into script? (y/n)" bake
+  [[ ! -n BAKE=y ]] && read -p "bake bashlive into script? (y/n)" bake || bake="y"
   grep -E "^/ /.*" "$file" | sed 's/!//g' > $BASHLIVETMP.paths
   while read bashlivepath; do 
     path="${bashlivepath/\/ /}"
     cachefile="$BASHLIVETMP$path"
-    if [[ -f "$cachefile" ]]; then code="$( echo -e "$code\n"; cat "$cachefile")"; else
-      printf "$C_RED""bashdown> cannot find '$cachefile' (please run the application first to build cache) $C_NORMAL \n"; return 1; 
+    if [[ -f "$cachefile" ]]; then code="$( echo -e "$code"; cat "$cachefile")"; else
+      printf "$C_RED""bashdown> cannot find '$cachefile' (please source/run the application first to build cache) $C_NORMAL \n"; return 1; 
     fi
   done < $BASHLIVETMP.paths
+  echo -e "#!/bin/bash\n#\n# generated by www.bashlive.com" > $BASHLIVETMP.insert
   { IFS=''; cat "$file" | while read line; do
      [[ "$line" =~ ^"/ /" ]] && continue;
-     if [[ "$line" =~ ". " ]] && [[ "$line" =~ "bashlive" ]]; then printf "\n%s\n" "$code"; else echo "$line"; fi
-   done
-  } > $BASHLIVETMP.insert;
+     [[ "$line" =~ ^(\.|source) ]] && echo -e "$code\n" || echo "$line";
+    done
+  } >> $BASHLIVETMP.insert;
   echo "bashlive> writing backup to $BASHLIVETMP.backup"; cp "$file" "$BASHLIVETMP.backup";
   cp "$BASHLIVETMP.insert" "$file" || { printf "$C_RED""could not copy '$BASHLIVETMP.insert' to '$file' :($C_NORMAL\n"; return 1; }
 }
diff --git a/tests/bake b/tests/bake
--- a/tests/bake
+++ b/tests/bake
@@ -1,9 +1,10 @@
 testfile="/tmp/bashlivetest"
-test='. bashlive
+test='. '$(pwd)'/bashlive
 / /bash/function/string/trim!
+echo " i should be trimmed " | trim
 '
 echo "$test" > "$testfile"
 echo "please say 'y' to the following question"
-/ "$testfile"
-
+BAKE=y / "$testfile"
+chmod 755 $testfile && $testfile | grep -E "^i should be trimmed" && echo "trimming succesful" || echo "FAIL"
 
